services:
  - type: web
    name: minecraft-bot-service
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    buildFilter:
      paths:
        - package.json
        - index.js
        - server.js
